/*
 * Copyright 2017 47 Degrees, LLC. <http://www.47deg.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

CREATE TABLE countries
(
  iso2 character varying(4) NOT NULL PRIMARY KEY,
  iso3 character varying(4),
  name character varying(256) NOT NULL,
  continent character varying(16) NOT NULL
);

INSERT INTO countries(iso2,iso3,name,continent) VALUES
('AO','AGO','Angola','Africa'),
('BF','BFA','Burkina Faso','Africa'),
('BI','BDI','Burundi','Africa'),
('BJ','BEN','Benin','Africa'),
('BW','BWA','Botswana','Africa'),
('CD','COD','Congo (DRC)','Africa'),
('CF','CAF','Central African Republic','Africa'),
('CG','COG','Congo (Republic)','Africa'),
('CI','CIV','Côte d’Ivoire','Africa'),
('CM','CMR','Cameroon','Africa'),
('CV','CPV','Cape Verde','Africa'),
('DJ','DJI','Djibouti','Africa'),
('DZ','DZA','Algeria','Africa'),
('EG','EGY','Egypt','Africa'),
('EH','ESH','Western Sahara','Africa'),
('ER','ERI','Eritrea','Africa'),
('ET','ETH','Ethiopia','Africa'),
('GA','GAB','Gabon','Africa'),
('GH','GHA','Ghana','Africa'),
('GM','GMB','Gambia','Africa'),
('GN','GIN','Guinea','Africa'),
('GQ','GNQ','Equatorial Guinea','Africa'),
('GW','GNB','Guinea-Bissau','Africa'),
('KE','KEN','Kenya','Africa'),
('KM','COM','Comoros','Africa'),
('LR','LBR','Liberia','Africa'),
('LS','LSO','Lesotho','Africa'),
('LY','LBY','Libya','Africa'),
('MA','MAR','Morocco','Africa'),
('MG','MDG','Madagascar','Africa'),
('ML','MLI','Mali','Africa'),
('MR','MRT','Mauritania','Africa'),
('MU','MUS','Mauritius','Africa'),
('MW','MWI','Malawi','Africa'),
('MZ','MOZ','Mozambique','Africa'),
('NA','NAM','Namibia','Africa'),
('NE','NER','Niger','Africa'),
('NG','NGA','Nigeria','Africa'),
('RE','REU','Réunion','Africa'),
('RW','RWA','Rwanda','Africa'),
('SC','SYC','Seychelles','Africa'),
('SD','SDN','Sudan','Africa'),
('SH','SHN','St. Helena','Africa'),
('SL','SLE','Sierra Leone','Africa'),
('SN','SEN','Senegal','Africa'),
('SO','SOM','Somalia','Africa'),
('SS','SSD','South Sudan','Africa'),
('ST','STP','São Tomé & Príncipe','Africa'),
('SZ','SWZ','Swaziland','Africa'),
('TD','TCD','Chad','Africa'),
('TG','TGO','Togo','Africa'),
('TN','TUN','Tunisia','Africa'),
('TZ','TZA','Tanzania','Africa'),
('UG','UGA','Uganda','Africa'),
('YT','MYT','Mayotte','Africa'),
('ZA','ZAF','South Africa','Africa'),
('ZM','ZMB','Zambia','Africa'),
('ZW','ZWE','Zimbabwe','Africa'),
('AG','ATG','Antigua & Barbuda','Americas'),
('AI','AIA','Anguilla','Americas'),
('AN','ANT','Netherlands Antilles','Americas'),
('AR','ARG','Argentina','Americas'),
('AW','ABW','Aruba','Americas'),
('BB','BRB','Barbados','Americas'),
('BL','BLM','St. Barthélemy','Americas'),
('BM','BMU','Bermuda','Americas'),
('BO','BOL','Bolivia','Americas'),
('BQ','BES','Caribbean Netherlands','Americas'),
('BR','BRA','Brazil','Americas'),
('BS','BHS','Bahamas','Americas'),
('BZ','BLZ','Belize','Americas'),
('CA','CAN','Canada','Americas'),
('CL','CHL','Chile','Americas'),
('CO','COL','Colombia','Americas'),
('CR','CRI','Costa Rica','Americas'),
('CU','CUB','Cuba','Americas'),
('CW','CUW','Curaçao','Americas'),
('DM','DMA','Dominica','Americas'),
('DO','DOM','Dominican Republic','Americas'),
('EC','ECU','Ecuador','Americas'),
('FK','FLK','Falkland Islands (Islas Malvinas)','Americas'),
('GD','GRD','Grenada','Americas'),
('GF','GUF','French Guiana','Americas'),
('GL','GRL','Greenland','Americas'),
('GP','GLP','Guadeloupe','Americas'),
('GT','GTM','Guatemala','Americas'),
('GY','GUY','Guyana','Americas'),
('HN','HND','Honduras','Americas'),
('HT','HTI','Haiti','Americas'),
('JM','JAM','Jamaica','Americas'),
('KN','KNA','St. Kitts & Nevis','Americas'),
('KY','CYM','Cayman Islands','Americas'),
('LC','LCA','St. Lucia','Americas'),
('MF','MAF','St. Martin','Americas'),
('MQ','MTQ','Martinique','Americas'),
('MS','MSR','Montserrat','Americas'),
('MX','MEX','Mexico','Americas'),
('NI','NIC','Nicaragua','Americas'),
('PA','PAN','Panama','Americas'),
('PE','PER','Peru','Americas'),
('PM','SPM','St. Pierre & Miquelon','Americas'),
('PR','PRI','Puerto Rico','Americas'),
('PY','PRY','Paraguay','Americas'),
('SR','SUR','Suriname','Americas'),
('SV','SLV','El Salvador','Americas'),
('SX','SXM','Sint Maarten','Americas'),
('TC','TCA','Turks & Caicos Islands','Americas'),
('TT','TTO','Trinidad & Tobago','Americas'),
('US','USA','United States','Americas'),
('UY','URY','Uruguay','Americas'),
('VC','VCT','St. Vincent & Grenadines','Americas'),
('VE','VEN','Venezuela','Americas'),
('VG','VGB','British Virgin Islands','Americas'),
('VI','VIR','U.S. Virgin Islands','Americas'),
('AE','ARE','United Arab Emirates','Asia'),
('AF','AFG','Afghanistan','Asia'),
('AM','ARM','Armenia','Asia'),
('AZ','AZE','Azerbaijan','Asia'),
('BD','BGD','Bangladesh','Asia'),
('BH','BHR','Bahrain','Asia'),
('BN','BRN','Brunei','Asia'),
('BT','BTN','Bhutan','Asia'),
('CC','CCK','Cocos (Keeling) Islands','Asia'),
('CN','CHN','China','Asia'),
('CX','CXR','Christmas Island','Asia'),
('GE','GEO','Georgia','Asia'),
('HK','HKG','Hong Kong','Asia'),
('ID','IDN','Indonesia','Asia'),
('IL','ISR','Israel','Asia'),
('IN','IND','India','Asia'),
('IO','IOT','British Indian Ocean Territory','Asia'),
('IQ','IRQ','Iraq','Asia'),
('IR','IRN','Iran','Asia'),
('JO','JOR','Jordan','Asia'),
('JP','JPN','Japan','Asia'),
('KG','KGZ','Kyrgyzstan','Asia'),
('KH','KHM','Cambodia','Asia'),
('KP','PRK','North Korea','Asia'),
('KR','KOR','South Korea','Asia'),
('KW','KWT','Kuwait','Asia'),
('KZ','KAZ','Kazakhstan','Asia'),
('LA','LAO','Laos','Asia'),
('LB','LBN','Lebanon','Asia'),
('LK','LKA','Sri Lanka','Asia'),
('MM','MMR','Myanmar (Burma)','Asia'),
('MN','MNG','Mongolia','Asia'),
('MO','MAC','Macau','Asia'),
('MV','MDV','Maldives','Asia'),
('MY','MYS','Malaysia','Asia'),
('NP','NPL','Nepal','Asia'),
('OM','OMN','Oman','Asia'),
('PH','PHL','Philippines','Asia'),
('PK','PAK','Pakistan','Asia'),
('PS','PSE','Palestine','Asia'),
('QA','QAT','Qatar','Asia'),
('SA','SAU','Saudi Arabia','Asia'),
('SG','SGP','Singapore','Asia'),
('SY','SYR','Syria','Asia'),
('TH','THA','Thailand','Asia'),
('TJ','TJK','Tajikistan','Asia'),
('TM','TKM','Turkmenistan','Asia'),
('TR','TUR','Turkey','Asia'),
('TW','TWN','Taiwan','Asia'),
('UZ','UZB','Uzbekistan','Asia'),
('VN','VNM','Vietnam','Asia'),
('YE','YEM','Yemen','Asia'),
('AD','AND','Andorra','Europe'),
('AL','ALB','Albania','Europe'),
('AT','AUT','Austria','Europe'),
('AX','ALA','Åland Islands','Europe'),
('BA','BIH','Bosnia & Herzegovina','Europe'),
('BE','BEL','Belgium','Europe'),
('BG','BGR','Bulgaria','Europe'),
('BY','BLR','Belarus','Europe'),
('CH','CHE','Switzerland','Europe'),
('CS','SCG','Serbia and Montenegro','Europe'),
('CY','CYP','Cyprus','Europe'),
('CZ','CZE','Czech Republic','Europe'),
('DE','DEU','Germany','Europe'),
('DK','DNK','Denmark','Europe'),
('EA',null,'Ceuta & Melilla','Europe'),
('EE','EST','Estonia','Europe'),
('ES','ESP','Spain','Europe'),
('FI','FIN','Finland','Europe'),
('FO','FRO','Faroe Islands','Europe'),
('FR','FRA','France','Europe'),
('GB','GBR','United Kingdom','Europe'),
('GG','GGY','Guernsey','Europe'),
('GI','GIB','Gibraltar','Europe'),
('GR','GRC','Greece','Europe'),
('HR','HRV','Croatia','Europe'),
('HU','HUN','Hungary','Europe'),
('IC',null,'Canary Islands','Europe'),
('IE','IRL','Ireland','Europe'),
('IM','IMN','Isle of Man','Europe'),
('IS','ISL','Iceland','Europe'),
('IT','ITA','Italy','Europe'),
('JE','JEY','Jersey','Europe'),
('LI','LIE','Liechtenstein','Europe'),
('LT','LTU','Lithuania','Europe'),
('LU','LUX','Luxembourg','Europe'),
('LV','LVA','Latvia','Europe'),
('MC','MCO','Monaco','Europe'),
('MD','MDA','Moldova','Europe'),
('ME','MNE','Montenegro','Europe'),
('MK','MKD','Macedonia (FYROM)','Europe'),
('MT','MLT','Malta','Europe'),
('NL','NLD','Netherlands','Europe'),
('NO','NOR','Norway','Europe'),
('PL','POL','Poland','Europe'),
('PT','PRT','Portugal','Europe'),
('RO','ROU','Romania','Europe'),
('RS','SRB','Serbia','Europe'),
('RU','RUS','Russia','Europe'),
('SE','SWE','Sweden','Europe'),
('SI','SVN','Slovenia','Europe'),
('SJ','SJM','Svalbard & Jan Mayen','Europe'),
('SK','SVK','Slovakia','Europe'),
('SM','SMR','San Marino','Europe'),
('UA','UKR','Ukraine','Europe'),
('VA','VAT','Vatican City','Europe'),
('XK','XKX','Kosovo','Europe'),
('AS','ASM','American Samoa','Oceania'),
('AU','AUS','Australia','Oceania'),
('CK','COK','Cook Islands','Oceania'),
('FJ','FJI','Fiji','Oceania'),
('FM','FSM','Micronesia','Oceania'),
('GU','GUM','Guam','Oceania'),
('KI','KIR','Kiribati','Oceania'),
('MH','MHL','Marshall Islands','Oceania'),
('MP','MNP','Northern Mariana Islands','Oceania'),
('NC','NCL','New Caledonia','Oceania'),
('NF','NFK','Norfolk Island','Oceania'),
('NR','NRU','Nauru','Oceania'),
('NU','NIU','Niue','Oceania'),
('NZ','NZL','New Zealand','Oceania'),
('PF','PYF','French Polynesia','Oceania'),
('PG','PNG','Papua New Guinea','Oceania'),
('PN','PCN','Pitcairn Islands','Oceania'),
('PW','PLW','Palau','Oceania'),
('SB','SLB','Solomon Islands','Oceania'),
('TK','TKL','Tokelau','Oceania'),
('TL','TLS','Timor-Leste','Oceania'),
('TO','TON','Tonga','Oceania'),
('TV','TUV','Tuvalu','Oceania'),
('UM','UMI','U.S. Outlying Islands','Oceania'),
('VU','VUT','Vanuatu','Oceania'),
('WF','WLF','Wallis & Futuna','Oceania'),
('WS','WSM','Samoa','Oceania');