CREATE TABLE countries
(
  id serial NOT NULL PRIMARY KEY,
  iso2 character varying(4) NOT NULL,
  iso3 character varying(4),
  name character varying(256) NOT NULL,
  continent character varying(16) NOT NULL
);

INSERT INTO countries(iso2,iso3,name,continent) VALUES
('AO','AGO','Angola','Africa'),
('BF','BFA','Burkina Faso','Africa'),
('BI','BDI','Burundi','Africa'),
('BJ','BEN','Benin','Africa'),
('BW','BWA','Botswana','Africa'),
('CD','COD','Congo (DRC)','Africa'),
('CF','CAF','Central African Republic','Africa'),
('CG','COG','Congo (Republic)','Africa'),
('CI','CIV','Côte d’Ivoire','Africa'),
('CM','CMR','Cameroon','Africa'),
('CV','CPV','Cape Verde','Africa'),
('DJ','DJI','Djibouti','Africa'),
('DZ','DZA','Algeria','Africa'),
('EG','EGY','Egypt','Africa'),
('EH','ESH','Western Sahara','Africa'),
('ER','ERI','Eritrea','Africa'),
('ET','ETH','Ethiopia','Africa'),
('GA','GAB','Gabon','Africa'),
('GH','GHA','Ghana','Africa'),
('GM','GMB','Gambia','Africa'),
('GN','GIN','Guinea','Africa'),
('GQ','GNQ','Equatorial Guinea','Africa'),
('GW','GNB','Guinea-Bissau','Africa'),
('KE','KEN','Kenya','Africa'),
('KM','COM','Comoros','Africa'),
('LR','LBR','Liberia','Africa'),
('LS','LSO','Lesotho','Africa'),
('LY','LBY','Libya','Africa'),
('MA','MAR','Morocco','Africa'),
('MG','MDG','Madagascar','Africa'),
('ML','MLI','Mali','Africa'),
('MR','MRT','Mauritania','Africa'),
('MU','MUS','Mauritius','Africa'),
('MW','MWI','Malawi','Africa'),
('MZ','MOZ','Mozambique','Africa'),
('NA','NAM','Namibia','Africa'),
('NE','NER','Niger','Africa'),
('NG','NGA','Nigeria','Africa'),
('RE','REU','Réunion','Africa'),
('RW','RWA','Rwanda','Africa'),
('SC','SYC','Seychelles','Africa'),
('SD','SDN','Sudan','Africa'),
('SH','SHN','St. Helena','Africa'),
('SL','SLE','Sierra Leone','Africa'),
('SN','SEN','Senegal','Africa'),
('SO','SOM','Somalia','Africa'),
('SS','SSD','South Sudan','Africa'),
('ST','STP','São Tomé & Príncipe','Africa'),
('SZ','SWZ','Swaziland','Africa'),
('TD','TCD','Chad','Africa'),
('TG','TGO','Togo','Africa'),
('TN','TUN','Tunisia','Africa'),
('TZ','TZA','Tanzania','Africa'),
('UG','UGA','Uganda','Africa'),
('YT','MYT','Mayotte','Africa'),
('ZA','ZAF','South Africa','Africa'),
('ZM','ZMB','Zambia','Africa'),
('ZW','ZWE','Zimbabwe','Africa'),
('AG','ATG','Antigua & Barbuda','America'),
('AI','AIA','Anguilla','America'),
('AN','ANT','Netherlands Antilles','America'),
('AR','ARG','Argentina','America'),
('AW','ABW','Aruba','America'),
('BB','BRB','Barbados','America'),
('BL','BLM','St. Barthélemy','America'),
('BM','BMU','Bermuda','America'),
('BO','BOL','Bolivia','America'),
('BQ','BES','Caribbean Netherlands','America'),
('BR','BRA','Brazil','America'),
('BS','BHS','Bahamas','America'),
('BZ','BLZ','Belize','America'),
('CA','CAN','Canada','America'),
('CL','CHL','Chile','America'),
('CO','COL','Colombia','America'),
('CR','CRI','Costa Rica','America'),
('CU','CUB','Cuba','America'),
('CW','CUW','Curaçao','America'),
('DM','DMA','Dominica','America'),
('DO','DOM','Dominican Republic','America'),
('EC','ECU','Ecuador','America'),
('FK','FLK','Falkland Islands (Islas Malvinas)','America'),
('GD','GRD','Grenada','America'),
('GF','GUF','French Guiana','America'),
('GL','GRL','Greenland','America'),
('GP','GLP','Guadeloupe','America'),
('GT','GTM','Guatemala','America'),
('GY','GUY','Guyana','America'),
('HN','HND','Honduras','America'),
('HT','HTI','Haiti','America'),
('JM','JAM','Jamaica','America'),
('KN','KNA','St. Kitts & Nevis','America'),
('KY','CYM','Cayman Islands','America'),
('LC','LCA','St. Lucia','America'),
('MF','MAF','St. Martin','America'),
('MQ','MTQ','Martinique','America'),
('MS','MSR','Montserrat','America'),
('MX','MEX','Mexico','America'),
('NI','NIC','Nicaragua','America'),
('PA','PAN','Panama','America'),
('PE','PER','Peru','America'),
('PM','SPM','St. Pierre & Miquelon','America'),
('PR','PRI','Puerto Rico','America'),
('PY','PRY','Paraguay','America'),
('SR','SUR','Suriname','America'),
('SV','SLV','El Salvador','America'),
('SX','SXM','Sint Maarten','America'),
('TC','TCA','Turks & Caicos Islands','America'),
('TT','TTO','Trinidad & Tobago','America'),
('US','USA','United States','America'),
('UY','URY','Uruguay','America'),
('VC','VCT','St. Vincent & Grenadines','America'),
('VE','VEN','Venezuela','America'),
('VG','VGB','British Virgin Islands','America'),
('VI','VIR','U.S. Virgin Islands','America'),
('AE','ARE','United Arab Emirates','Asia'),
('AF','AFG','Afghanistan','Asia'),
('AM','ARM','Armenia','Asia'),
('AZ','AZE','Azerbaijan','Asia'),
('BD','BGD','Bangladesh','Asia'),
('BH','BHR','Bahrain','Asia'),
('BN','BRN','Brunei','Asia'),
('BT','BTN','Bhutan','Asia'),
('CC','CCK','Cocos (Keeling) Islands','Asia'),
('CN','CHN','China','Asia'),
('CX','CXR','Christmas Island','Asia'),
('GE','GEO','Georgia','Asia'),
('HK','HKG','Hong Kong','Asia'),
('ID','IDN','Indonesia','Asia'),
('IL','ISR','Israel','Asia'),
('IN','IND','India','Asia'),
('IO','IOT','British Indian Ocean Territory','Asia'),
('IQ','IRQ','Iraq','Asia'),
('IR','IRN','Iran','Asia'),
('JO','JOR','Jordan','Asia'),
('JP','JPN','Japan','Asia'),
('KG','KGZ','Kyrgyzstan','Asia'),
('KH','KHM','Cambodia','Asia'),
('KP','PRK','North Korea','Asia'),
('KR','KOR','South Korea','Asia'),
('KW','KWT','Kuwait','Asia'),
('KZ','KAZ','Kazakhstan','Asia'),
('LA','LAO','Laos','Asia'),
('LB','LBN','Lebanon','Asia'),
('LK','LKA','Sri Lanka','Asia'),
('MM','MMR','Myanmar (Burma)','Asia'),
('MN','MNG','Mongolia','Asia'),
('MO','MAC','Macau','Asia'),
('MV','MDV','Maldives','Asia'),
('MY','MYS','Malaysia','Asia'),
('NP','NPL','Nepal','Asia'),
('OM','OMN','Oman','Asia'),
('PH','PHL','Philippines','Asia'),
('PK','PAK','Pakistan','Asia'),
('PS','PSE','Palestine','Asia'),
('QA','QAT','Qatar','Asia'),
('SA','SAU','Saudi Arabia','Asia'),
('SG','SGP','Singapore','Asia'),
('SY','SYR','Syria','Asia'),
('TH','THA','Thailand','Asia'),
('TJ','TJK','Tajikistan','Asia'),
('TM','TKM','Turkmenistan','Asia'),
('TR','TUR','Turkey','Asia'),
('TW','TWN','Taiwan','Asia'),
('UZ','UZB','Uzbekistan','Asia'),
('VN','VNM','Vietnam','Asia'),
('YE','YEM','Yemen','Asia'),
('AD','AND','Andorra','Europe'),
('AL','ALB','Albania','Europe'),
('AT','AUT','Austria','Europe'),
('AX','ALA','Åland Islands','Europe'),
('BA','BIH','Bosnia & Herzegovina','Europe'),
('BE','BEL','Belgium','Europe'),
('BG','BGR','Bulgaria','Europe'),
('BY','BLR','Belarus','Europe'),
('CH','CHE','Switzerland','Europe'),
('CS','SCG','Serbia and Montenegro','Europe'),
('CY','CYP','Cyprus','Europe'),
('CZ','CZE','Czech Republic','Europe'),
('DE','DEU','Germany','Europe'),
('DK','DNK','Denmark','Europe'),
('EA',null,'Ceuta & Melilla','Europe'),
('EE','EST','Estonia','Europe'),
('ES','ESP','Spain','Europe'),
('FI','FIN','Finland','Europe'),
('FO','FRO','Faroe Islands','Europe'),
('FR','FRA','France','Europe'),
('GB','GBR','United Kingdom','Europe'),
('GG','GGY','Guernsey','Europe'),
('GI','GIB','Gibraltar','Europe'),
('GR','GRC','Greece','Europe'),
('HR','HRV','Croatia','Europe'),
('HU','HUN','Hungary','Europe'),
('IC',null,'Canary Islands','Europe'),
('IE','IRL','Ireland','Europe'),
('IM','IMN','Isle of Man','Europe'),
('IS','ISL','Iceland','Europe'),
('IT','ITA','Italy','Europe'),
('JE','JEY','Jersey','Europe'),
('LI','LIE','Liechtenstein','Europe'),
('LT','LTU','Lithuania','Europe'),
('LU','LUX','Luxembourg','Europe'),
('LV','LVA','Latvia','Europe'),
('MC','MCO','Monaco','Europe'),
('MD','MDA','Moldova','Europe'),
('ME','MNE','Montenegro','Europe'),
('MK','MKD','Macedonia (FYROM)','Europe'),
('MT','MLT','Malta','Europe'),
('NL','NLD','Netherlands','Europe'),
('NO','NOR','Norway','Europe'),
('PL','POL','Poland','Europe'),
('PT','PRT','Portugal','Europe'),
('RO','ROU','Romania','Europe'),
('RS','SRB','Serbia','Europe'),
('RU','RUS','Russia','Europe'),
('SE','SWE','Sweden','Europe'),
('SI','SVN','Slovenia','Europe'),
('SJ','SJM','Svalbard & Jan Mayen','Europe'),
('SK','SVK','Slovakia','Europe'),
('SM','SMR','San Marino','Europe'),
('UA','UKR','Ukraine','Europe'),
('VA','VAT','Vatican City','Europe'),
('XK','XKX','Kosovo','Europe'),
('AS','ASM','American Samoa','Oceania'),
('AU','AUS','Australia','Oceania'),
('CK','COK','Cook Islands','Oceania'),
('FJ','FJI','Fiji','Oceania'),
('FM','FSM','Micronesia','Oceania'),
('GU','GUM','Guam','Oceania'),
('KI','KIR','Kiribati','Oceania'),
('MH','MHL','Marshall Islands','Oceania'),
('MP','MNP','Northern Mariana Islands','Oceania'),
('NC','NCL','New Caledonia','Oceania'),
('NF','NFK','Norfolk Island','Oceania'),
('NR','NRU','Nauru','Oceania'),
('NU','NIU','Niue','Oceania'),
('NZ','NZL','New Zealand','Oceania'),
('PF','PYF','French Polynesia','Oceania'),
('PG','PNG','Papua New Guinea','Oceania'),
('PN','PCN','Pitcairn Islands','Oceania'),
('PW','PLW','Palau','Oceania'),
('SB','SLB','Solomon Islands','Oceania'),
('TK','TKL','Tokelau','Oceania'),
('TL','TLS','Timor-Leste','Oceania'),
('TO','TON','Tonga','Oceania'),
('TV','TUV','Tuvalu','Oceania'),
('UM','UMI','U.S. Outlying Islands','Oceania'),
('VU','VUT','Vanuatu','Oceania'),
('WF','WLF','Wallis & Futuna','Oceania'),
('WS','WSM','Samoa','Oceania');