package cards.nine.domain.account

/**
  * An AndroidId is a number, written as a hexadecimal 64-bit
  *  (16 characters) string, which uniquely identifies an Android device.
  */
case class AndroidId(value: String) extends AnyVal

/**
  * An Email address that identifies an Android User Account.
  */
case class Email(value: String) extends AnyVal

/**
  * A DeviceToken identifies a device's mailbox, for notifications
  */
case class DeviceToken(value: String) extends AnyVal

/**
  * A SessionToken is an alias for a User's account, used within the context
  * of the NineCards. The SessionToken is generated by the backend for the user
  * upon signup. The client then has to pass the sessionToken as the account id.
  */
case class SessionToken(value: String) extends AnyVal

/**
  *  A GoogleIdToken is an OAuth Token, granted by Google API to the client's user.
  *  This is used upon signup, to check the identity and email of a client's account.
  */
case class GoogleIdToken(value: String) extends AnyVal

/**
  *  An ApiKey is a hash key, used to authenticate the client's requests messages.
  *  The request must contain a X-Auth-Token header, whose value is part of the message,
  *  hashed through the Sha512 algorithm with an Api Key.
  */
case class ApiKey(value: String) extends AnyVal